tunnel: <UUID>
credentials-file: /home/<user>/.cloudflared/<UUID>.json
ingress:
  - hostname: example.com
    service: http://127.0.0.1:8080
  - hostname: www.example.com
    service: http://127.0.0.1:8080
  - service: http_status:404
